name: test_milestone
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core + Firestore
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1

  # Geolocation and geo queries
  geolocator: ^11.1.0
  geoflutterfire_plus: ^0.0.33

  # State management (simple example uses Provider)
  provider: ^6.1.2
  cupertino_icons: ^1.0.2

  #multi select drop down
  multi_dropdown: ^3.0.1

  #to pick image from gallery/camera
  #NOTE FOR IOS THIS NEEDS SPECIAL PERMISSIONS IN info.plist
  image_picker: ^1.2.0

  #chat user interface
  flutter_chat_ui: ^2.9.1

  #lets user send messages with chat
  flutter_chat_core: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
